package ru.stqa.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.steps.CRUDlsForGroup;
import ru.stqa.addressbook.tests.TestBase;

import java.util.*;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class GroupDeletedTests extends TestBase {
  @Test
  public void deleted() {
    openPage("groups");
    CRUDlsForGroup deleted = new CRUDlsForGroup(driver);
    int size = deleted.CheckCreationGroups();
    if (size==0){ deleted.CreationGroup();size++;}
    deleted.DeletedGroup();
    int AfterSize = deleted.CheckCreationGroups();
    assertTrue(size > AfterSize);

  }
}
