package ru.stqa.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.models.GroupData;
import ru.stqa.addressbook.manager.GroupHelper;

import java.util.ArrayList;
import java.util.Random;


public class GroupDeletedTests extends TestBase{
  @Test
  public void groupsDeletedTests() {
    GroupHelper groups = app.groups();
    if (groups.getGroupsCount()==0){ groups.createGroup(new GroupData().withName("some name"));}

    var oldGroups = app.groups().getListGroups();

    var rnd = new Random();
    var index = rnd.nextInt(oldGroups.size());

    groups.deleteElement(oldGroups.get(index));
    var newGroups = app.groups().getListGroups();

    var expectedList = new ArrayList<>(oldGroups);
    expectedList.remove(index);

    Assertions.assertEquals(newGroups, expectedList);

  }

  @Test
  public void canRemoveAllGroupsAtOnce() {
    GroupHelper groups = app.groups();

    if (groups.getGroupsCount()==0){ groups.createGroup(new GroupData().withName("some name"));}

    groups.deleteAllGroup();

    Assertions.assertEquals(0, app.groups().getGroupsCount());
  }
}
