package ru.stqa.addressbook.tests;// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.models.GroupData;
import ru.stqa.addressbook.steps.CRUDlsForGroup;
import ru.stqa.addressbook.steps.TestBase;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class GroupDeletedTests extends TestBase {
  @Test
  public void deleted() {
    app.openPage("groups");
    CRUDlsForGroup actions = new CRUDlsForGroup(app.driver);
    int size = actions.CheckCreationGroups();

    if (size==0){ actions.CreationGroup(new GroupData().withName("some name"));size++;}
    actions.DeletedGroup();

    int AfterSize = actions.CheckCreationGroups();
    assertTrue(size > AfterSize);

  }
}
