package ru.stqa.addressbook.tests;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.manager.GroupHelper;
import ru.stqa.addressbook.models.GroupData;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class GroupCreationTests extends TestBase {

  @Test
  public void creationGroup(){
    GroupHelper groups = app.groups();

    int startedGroups = groups.CheckCreationGroups();

    groups.CreationGroup(new GroupData().withName("some name"));

    int afterGroups = groups.CheckCreationGroups();

    assertTrue(startedGroups < afterGroups);

  }
}
