package ru.stqa.addressbook.tests;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.manager.GroupHelper;
import ru.stqa.addressbook.models.GroupData;
import static org.junit.jupiter.api.Assertions.assertTrue;

public class GroupCreationTests extends TestBase {

  @Test
  public void creationGroup(){
    GroupHelper actions = app.groups();

    int startedGroups = actions.CheckCreationGroups();

    actions.CreationGroup(new GroupData().withName("some name"));

    int afterGroups = actions.CheckCreationGroups();

    assertTrue(startedGroups < afterGroups);

  }
}
