package ru.stqa.addressbook.tests;
// Generated by Selenium IDE
import org.junit.jupiter.api.Test;
import ru.stqa.addressbook.models.GroupData;
import ru.stqa.addressbook.steps.CRUDlsForGroup;
import ru.stqa.addressbook.steps.TestBase;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class GroupCreationTests extends TestBase {

  @Test
  public void creationGroup(){
    app.openPage("groups");
    CRUDlsForGroup actions = new CRUDlsForGroup(app.driver);

    int startedGroups = actions.CheckCreationGroups();

    var emptyGroup = new GroupData();
    var groupWithName = emptyGroup.withName("some Name");
    actions.CreationGroup(groupWithName);

    actions.GoToLink();
    int afterGroups = actions.CheckCreationGroups();

    assertTrue(startedGroups < afterGroups);

  }
}
