package ru.stqa.addressbook;// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.*;

public class GroupDeletedTests {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeEach
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    driver.get("http://localhost/addressbook/");
    driver.manage().window().setSize(new Dimension(1721, 1033));
    driver.findElement(By.name("user")).click();
    driver.findElement(By.name("user")).sendKeys("admin");
    driver.findElement(By.name("pass")).sendKeys("secret");
    driver.findElement(By.xpath("//input[@value='Login']")).click();
    driver.findElement(By.linkText("groups")).click();

    List<WebElement> groups = driver.findElements(By.cssSelector("span.group"));

    if (!groups.isEmpty()) {
      System.out.println("Группы найдены: " + groups.size());
    } else {
      System.out.println("Групп нет. Отображается только hr/bp.");
    }
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void deleted() {
    driver.findElement(By.name("selected[]")).click();
    driver.findElement(By.xpath("(//input[@name=\'delete\'])[2]")).click();
    driver.findElement(By.linkText("group page")).click();
  }
}
